export const erpModules = [
    {
        id: 1,
        name: 'Sales',
        icon: 'TrendingUp',
        color: 'blue',
        url: 'https://sales.erp.company.com',
        requiredRole: 'sales_manager',
    },
    {
        id: 2,
        name: 'Inventory',
        icon: 'Package',
        color: 'green',
        url: 'https://inventory.erp.company.com',
        requiredRole: 'admin',
    },
    {
        id: 3,
        name: 'Finance',
        icon: 'DollarSign',
        color: 'yellow',
        url: 'https://finance.erp.company.com',
        requiredRole: 'admin',
    },
    {
        id: 4,
        name: 'HR',
        icon: 'Users',
        color: 'purple',
        url: 'https://hr.erp.company.com',
        requiredRole: 'hr_manager',
    },
    {
        id: 5,
        name: 'Procurement',
        icon: 'ShoppingCart',
        color: 'orange',
        url: 'https://procurement.erp.company.com',
        requiredRole: 'admin',
    },
    {
        id: 6,
        name: 'Manufacturing',
        icon: 'Factory',
        color: 'red',
        url: 'https://manufacturing.erp.company.com',
        requiredRole: 'admin',
    },
    {
        id: 7,
        name: 'CRM',
        icon: 'HeartHandshake',
        color: 'pink',
        url: 'https://crm.erp.company.com',
        requiredRole: 'sales_manager',
    },
    {
        id: 8,
        name: 'Analytics',
        icon: 'BarChart3',
        color: 'indigo',
        url: 'https://analytics.erp.company.com',
        requiredRole: 'admin',
    },
    {
        id: 9,
        name: 'Projects',
        icon: 'Briefcase',
        color: 'cyan',
        url: 'https://projects.erp.company.com',
        requiredRole: 'admin',
    },
    {
        id: 10,
        name: 'Support',
        icon: 'Headphones',
        color: 'gray',
        url: 'https://support.erp.company.com',
        requiredRole: 'admin',
    },
];
